backend:
  name: github
  branch: master
  repo: achyutarao-in/achyutarao-in-content
  base_url: https://achyutarao-in-oauth-server.glitch.me/

media_folder: 'src/assets/images/uploads' # Folder where user uploaded files should go
public_folder: 'assets/images/uploads'
publish_mode: editorial_workflow

collections: 
  - name: landing
    label: Landing Page
    files: 
      - label: Text Bits
        name: text_bits
        file: src/content/landing/text_bits.json
        fields:
          - label: BHS Section
            name: bhs
            widget: list
            field: {label: Para, name: para, widget: text}
          - label: Early Life Section
            name: earlylife
            widget: list
            field: {label: Para, name: para, widget: text}
          - label: Citizen Ads Section
            name: citizenads
            widget: list
            field: {label: Para, name: para, widget: text}
          - label: Family and Friends Section
            name: family
            widget: list
            field: {label: Para, name: para, widget: text}