backend:
  name: github
  branch: master
  repo: achyutarao-in/achyutarao-in.github.io
  base_url: https://achyutarao-in-oauth-server.glitch.me/

# For local development, uncomment following line and run `npx netlify-cms-proxy-server`
# local_backend: true

site_url: https://www.achyutarao.in
display_url: https://www.achyutarao.in
logo_url: https://www.achyutarao.in/android-chrome-512x512.png

media_folder: 'src/assets/images/uploads' # Folder where user uploaded files should go
public_folder: 'assets/images/uploads'

collections: 
  - name: landing
    label: Landing Page
    files: 
      - label: Early Life Section
        name: earlylife
        widget: object
        collapsed: false
        file: 'src/content/landing/earlylife.json'
        fields: 
        - {label: Title, name: title, widget: string}
        - label: Images
          name: images
          widget: list
          field:
              label: Image
              name: image
              widget: image
        - label: Paras
          name: paras
          widget: list
          field:
              label: Text
              name: text
              widget: text
      - label: Balala Hakkula Sangham Section
        name: bhs
        widget: object
        collapsed: false
        file: 'src/content/landing/bhs.json'
        fields: 
        - {label: Title, name: title, widget: string}
        - label: Images
          name: images
          widget: list
          field:
              label: Image
              name: image
              widget: image
        - label: Paras
          name: paras
          widget: list
          field:
              label: Text
              name: text
              widget: text
      - label: Citizen Ads Section
        name: citizenads
        widget: object
        collapsed: false
        file: 'src/content/landing/citizenads.json'
        fields: 
        - {label: Title, name: title, widget: string}
        - label: Images
          name: images
          widget: list
          field:
              label: Image
              name: image
              widget: image
        - label: Paras
          name: paras
          widget: list
          field:
              label: Text
              name: text
              widget: text
      - label: Friends and Family Secion
        name: family
        widget: object
        collapsed: false
        file: 'src/content/landing/family.json'
        fields: 
        - {label: Title, name: title, widget: string}
        - label: Images
          name: images
          widget: list
          field:
              label: Image
              name: image
              widget: image
        - label: Paras
          name: paras
          widget: list
          field:
              label: Text
              name: text
              widget: text

          